//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eulei.com.MIS.ClientConnection.MISService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.eulei.com/MIS/", ConfigurationName="MISService.IMISService")]
    public interface IMISService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eulei.com/MIS/IMISService/getDate", ReplyAction="http://www.eulei.com/MIS/IMISService/getDateResponse")]
        string getDate();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMISServiceChannel : eulei.com.MIS.ClientConnection.MISService.IMISService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MISServiceClient : System.ServiceModel.ClientBase<eulei.com.MIS.ClientConnection.MISService.IMISService>, eulei.com.MIS.ClientConnection.MISService.IMISService {
        
        public MISServiceClient() {
        }
        
        public MISServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MISServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MISServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MISServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getDate() {
            return base.Channel.getDate();
        }
    }
}
