#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eulei.com.MIS.Contracts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EULEI_MIS")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertETB_COM(ETB_COM instance);
    partial void UpdateETB_COM(ETB_COM instance);
    partial void DeleteETB_COM(ETB_COM instance);
    partial void InsertETB_COMINFO(ETB_COMINFO instance);
    partial void UpdateETB_COMINFO(ETB_COMINFO instance);
    partial void DeleteETB_COMINFO(ETB_COMINFO instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::eulei.com.MIS.Contracts.Properties.Settings.Default.EULEI_MISConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ETB_COM> ETB_COM
		{
			get
			{
				return this.GetTable<ETB_COM>();
			}
		}
		
		public System.Data.Linq.Table<ETB_COMINFO> ETB_COMINFO
		{
			get
			{
				return this.GetTable<ETB_COMINFO>();
			}
		}
		
		public System.Data.Linq.Table<EVW_COMINFO> EVW_COMINFO
		{
			get
			{
				return this.GetTable<EVW_COMINFO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETB_COM")]
	public partial class ETB_COM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _COMID;
		
		private string _COMName;
		
		private string _COMEasyCode;
		
		private System.Nullable<int> _COMOrder;
		
		private EntitySet<ETB_COMINFO> _ETB_COMINFO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOMIDChanging(System.Guid value);
    partial void OnCOMIDChanged();
    partial void OnCOMNameChanging(string value);
    partial void OnCOMNameChanged();
    partial void OnCOMEasyCodeChanging(string value);
    partial void OnCOMEasyCodeChanged();
    partial void OnCOMOrderChanging(System.Nullable<int> value);
    partial void OnCOMOrderChanged();
    #endregion
		
		public ETB_COM()
		{
			this._ETB_COMINFO = new EntitySet<ETB_COMINFO>(new Action<ETB_COMINFO>(this.attach_ETB_COMINFO), new Action<ETB_COMINFO>(this.detach_ETB_COMINFO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid COMID
		{
			get
			{
				return this._COMID;
			}
			set
			{
				if ((this._COMID != value))
				{
					this.OnCOMIDChanging(value);
					this.SendPropertyChanging();
					this._COMID = value;
					this.SendPropertyChanged("COMID");
					this.OnCOMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string COMName
		{
			get
			{
				return this._COMName;
			}
			set
			{
				if ((this._COMName != value))
				{
					this.OnCOMNameChanging(value);
					this.SendPropertyChanging();
					this._COMName = value;
					this.SendPropertyChanged("COMName");
					this.OnCOMNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMEasyCode", DbType="NVarChar(50)")]
		public string COMEasyCode
		{
			get
			{
				return this._COMEasyCode;
			}
			set
			{
				if ((this._COMEasyCode != value))
				{
					this.OnCOMEasyCodeChanging(value);
					this.SendPropertyChanging();
					this._COMEasyCode = value;
					this.SendPropertyChanged("COMEasyCode");
					this.OnCOMEasyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMOrder", DbType="Int")]
		public System.Nullable<int> COMOrder
		{
			get
			{
				return this._COMOrder;
			}
			set
			{
				if ((this._COMOrder != value))
				{
					this.OnCOMOrderChanging(value);
					this.SendPropertyChanging();
					this._COMOrder = value;
					this.SendPropertyChanged("COMOrder");
					this.OnCOMOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ETB_COM_ETB_COMINFO", Storage="_ETB_COMINFO", ThisKey="COMID", OtherKey="COMID")]
		public EntitySet<ETB_COMINFO> ETB_COMINFO
		{
			get
			{
				return this._ETB_COMINFO;
			}
			set
			{
				this._ETB_COMINFO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ETB_COMINFO(ETB_COMINFO entity)
		{
			this.SendPropertyChanging();
			entity.ETB_COM = this;
		}
		
		private void detach_ETB_COMINFO(ETB_COMINFO entity)
		{
			this.SendPropertyChanging();
			entity.ETB_COM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETB_COMINFO")]
	public partial class ETB_COMINFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _COMINFOID;
		
		private string _COMINFOName;
		
		private string _COMINFOEasyCode;
		
		private string _COMINFOAddress;
		
		private string _COMINFOPostalCode;
		
		private string _COMINFOTEL;
		
		private string _COMINFOFax;
		
		private string _COMINFORemark;
		
		private bool _COMINFOCustomerServiceUnit;
		
		private bool _COMINFOBusCustomerServiceUnit;
		
		private System.Nullable<int> _COMINFOCOMINFOOrder;
		
		private System.Nullable<System.Guid> _COMID;
		
		private EntityRef<ETB_COM> _ETB_COM;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOMINFOIDChanging(System.Guid value);
    partial void OnCOMINFOIDChanged();
    partial void OnCOMINFONameChanging(string value);
    partial void OnCOMINFONameChanged();
    partial void OnCOMINFOEasyCodeChanging(string value);
    partial void OnCOMINFOEasyCodeChanged();
    partial void OnCOMINFOAddressChanging(string value);
    partial void OnCOMINFOAddressChanged();
    partial void OnCOMINFOPostalCodeChanging(string value);
    partial void OnCOMINFOPostalCodeChanged();
    partial void OnCOMINFOTELChanging(string value);
    partial void OnCOMINFOTELChanged();
    partial void OnCOMINFOFaxChanging(string value);
    partial void OnCOMINFOFaxChanged();
    partial void OnCOMINFORemarkChanging(string value);
    partial void OnCOMINFORemarkChanged();
    partial void OnCOMINFOCustomerServiceUnitChanging(bool value);
    partial void OnCOMINFOCustomerServiceUnitChanged();
    partial void OnCOMINFOBusCustomerServiceUnitChanging(bool value);
    partial void OnCOMINFOBusCustomerServiceUnitChanged();
    partial void OnCOMINFOCOMINFOOrderChanging(System.Nullable<int> value);
    partial void OnCOMINFOCOMINFOOrderChanged();
    partial void OnCOMIDChanging(System.Nullable<System.Guid> value);
    partial void OnCOMIDChanged();
    #endregion
		
		public ETB_COMINFO()
		{
			this._ETB_COM = default(EntityRef<ETB_COM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid COMINFOID
		{
			get
			{
				return this._COMINFOID;
			}
			set
			{
				if ((this._COMINFOID != value))
				{
					this.OnCOMINFOIDChanging(value);
					this.SendPropertyChanging();
					this._COMINFOID = value;
					this.SendPropertyChanged("COMINFOID");
					this.OnCOMINFOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string COMINFOName
		{
			get
			{
				return this._COMINFOName;
			}
			set
			{
				if ((this._COMINFOName != value))
				{
					this.OnCOMINFONameChanging(value);
					this.SendPropertyChanging();
					this._COMINFOName = value;
					this.SendPropertyChanged("COMINFOName");
					this.OnCOMINFONameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOEasyCode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string COMINFOEasyCode
		{
			get
			{
				return this._COMINFOEasyCode;
			}
			set
			{
				if ((this._COMINFOEasyCode != value))
				{
					this.OnCOMINFOEasyCodeChanging(value);
					this.SendPropertyChanging();
					this._COMINFOEasyCode = value;
					this.SendPropertyChanged("COMINFOEasyCode");
					this.OnCOMINFOEasyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOAddress", DbType="VarChar(MAX)")]
		public string COMINFOAddress
		{
			get
			{
				return this._COMINFOAddress;
			}
			set
			{
				if ((this._COMINFOAddress != value))
				{
					this.OnCOMINFOAddressChanging(value);
					this.SendPropertyChanging();
					this._COMINFOAddress = value;
					this.SendPropertyChanged("COMINFOAddress");
					this.OnCOMINFOAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOPostalCode", DbType="VarChar(10)")]
		public string COMINFOPostalCode
		{
			get
			{
				return this._COMINFOPostalCode;
			}
			set
			{
				if ((this._COMINFOPostalCode != value))
				{
					this.OnCOMINFOPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._COMINFOPostalCode = value;
					this.SendPropertyChanged("COMINFOPostalCode");
					this.OnCOMINFOPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOTEL", DbType="VarChar(50)")]
		public string COMINFOTEL
		{
			get
			{
				return this._COMINFOTEL;
			}
			set
			{
				if ((this._COMINFOTEL != value))
				{
					this.OnCOMINFOTELChanging(value);
					this.SendPropertyChanging();
					this._COMINFOTEL = value;
					this.SendPropertyChanged("COMINFOTEL");
					this.OnCOMINFOTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOFax", DbType="VarChar(50)")]
		public string COMINFOFax
		{
			get
			{
				return this._COMINFOFax;
			}
			set
			{
				if ((this._COMINFOFax != value))
				{
					this.OnCOMINFOFaxChanging(value);
					this.SendPropertyChanging();
					this._COMINFOFax = value;
					this.SendPropertyChanged("COMINFOFax");
					this.OnCOMINFOFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFORemark", DbType="VarChar(MAX)")]
		public string COMINFORemark
		{
			get
			{
				return this._COMINFORemark;
			}
			set
			{
				if ((this._COMINFORemark != value))
				{
					this.OnCOMINFORemarkChanging(value);
					this.SendPropertyChanging();
					this._COMINFORemark = value;
					this.SendPropertyChanged("COMINFORemark");
					this.OnCOMINFORemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOCustomerServiceUnit", DbType="Bit NOT NULL")]
		public bool COMINFOCustomerServiceUnit
		{
			get
			{
				return this._COMINFOCustomerServiceUnit;
			}
			set
			{
				if ((this._COMINFOCustomerServiceUnit != value))
				{
					this.OnCOMINFOCustomerServiceUnitChanging(value);
					this.SendPropertyChanging();
					this._COMINFOCustomerServiceUnit = value;
					this.SendPropertyChanged("COMINFOCustomerServiceUnit");
					this.OnCOMINFOCustomerServiceUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOBusCustomerServiceUnit", DbType="Bit NOT NULL")]
		public bool COMINFOBusCustomerServiceUnit
		{
			get
			{
				return this._COMINFOBusCustomerServiceUnit;
			}
			set
			{
				if ((this._COMINFOBusCustomerServiceUnit != value))
				{
					this.OnCOMINFOBusCustomerServiceUnitChanging(value);
					this.SendPropertyChanging();
					this._COMINFOBusCustomerServiceUnit = value;
					this.SendPropertyChanged("COMINFOBusCustomerServiceUnit");
					this.OnCOMINFOBusCustomerServiceUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOCOMINFOOrder", DbType="Int")]
		public System.Nullable<int> COMINFOCOMINFOOrder
		{
			get
			{
				return this._COMINFOCOMINFOOrder;
			}
			set
			{
				if ((this._COMINFOCOMINFOOrder != value))
				{
					this.OnCOMINFOCOMINFOOrderChanging(value);
					this.SendPropertyChanging();
					this._COMINFOCOMINFOOrder = value;
					this.SendPropertyChanged("COMINFOCOMINFOOrder");
					this.OnCOMINFOCOMINFOOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> COMID
		{
			get
			{
				return this._COMID;
			}
			set
			{
				if ((this._COMID != value))
				{
					if (this._ETB_COM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOMIDChanging(value);
					this.SendPropertyChanging();
					this._COMID = value;
					this.SendPropertyChanged("COMID");
					this.OnCOMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ETB_COM_ETB_COMINFO", Storage="_ETB_COM", ThisKey="COMID", OtherKey="COMID", IsForeignKey=true)]
		public ETB_COM ETB_COM
		{
			get
			{
				return this._ETB_COM.Entity;
			}
			set
			{
				ETB_COM previousValue = this._ETB_COM.Entity;
				if (((previousValue != value) 
							|| (this._ETB_COM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ETB_COM.Entity = null;
						previousValue.ETB_COMINFO.Remove(this);
					}
					this._ETB_COM.Entity = value;
					if ((value != null))
					{
						value.ETB_COMINFO.Add(this);
						this._COMID = value.COMID;
					}
					else
					{
						this._COMID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("ETB_COM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EVW_COMINFO")]
	public partial class EVW_COMINFO
	{
		
		private System.Guid _COMID;
		
		private string _COMName;
		
		private string _COMEasyCode;
		
		private System.Nullable<int> _COMOrder;
		
		private System.Guid _COMINFOID;
		
		private string _COMINFOName;
		
		private string _COMINFOEasyCode;
		
		private string _COMINFOAddress;
		
		private string _COMINFOPostalCode;
		
		private string _COMINFOTEL;
		
		private string _COMINFOFax;
		
		private string _COMINFORemark;
		
		private bool _COMINFOCustomerServiceUnit;
		
		private bool _COMINFOBusCustomerServiceUnit;
		
		private System.Nullable<int> _COMINFOCOMINFOOrder;
		
		public EVW_COMINFO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid COMID
		{
			get
			{
				return this._COMID;
			}
			set
			{
				if ((this._COMID != value))
				{
					this._COMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string COMName
		{
			get
			{
				return this._COMName;
			}
			set
			{
				if ((this._COMName != value))
				{
					this._COMName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMEasyCode", DbType="NVarChar(50)")]
		public string COMEasyCode
		{
			get
			{
				return this._COMEasyCode;
			}
			set
			{
				if ((this._COMEasyCode != value))
				{
					this._COMEasyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMOrder", DbType="Int")]
		public System.Nullable<int> COMOrder
		{
			get
			{
				return this._COMOrder;
			}
			set
			{
				if ((this._COMOrder != value))
				{
					this._COMOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid COMINFOID
		{
			get
			{
				return this._COMINFOID;
			}
			set
			{
				if ((this._COMINFOID != value))
				{
					this._COMINFOID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string COMINFOName
		{
			get
			{
				return this._COMINFOName;
			}
			set
			{
				if ((this._COMINFOName != value))
				{
					this._COMINFOName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOEasyCode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string COMINFOEasyCode
		{
			get
			{
				return this._COMINFOEasyCode;
			}
			set
			{
				if ((this._COMINFOEasyCode != value))
				{
					this._COMINFOEasyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOAddress", DbType="VarChar(MAX)")]
		public string COMINFOAddress
		{
			get
			{
				return this._COMINFOAddress;
			}
			set
			{
				if ((this._COMINFOAddress != value))
				{
					this._COMINFOAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOPostalCode", DbType="VarChar(10)")]
		public string COMINFOPostalCode
		{
			get
			{
				return this._COMINFOPostalCode;
			}
			set
			{
				if ((this._COMINFOPostalCode != value))
				{
					this._COMINFOPostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOTEL", DbType="VarChar(50)")]
		public string COMINFOTEL
		{
			get
			{
				return this._COMINFOTEL;
			}
			set
			{
				if ((this._COMINFOTEL != value))
				{
					this._COMINFOTEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOFax", DbType="VarChar(50)")]
		public string COMINFOFax
		{
			get
			{
				return this._COMINFOFax;
			}
			set
			{
				if ((this._COMINFOFax != value))
				{
					this._COMINFOFax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFORemark", DbType="VarChar(MAX)")]
		public string COMINFORemark
		{
			get
			{
				return this._COMINFORemark;
			}
			set
			{
				if ((this._COMINFORemark != value))
				{
					this._COMINFORemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOCustomerServiceUnit", DbType="Bit NOT NULL")]
		public bool COMINFOCustomerServiceUnit
		{
			get
			{
				return this._COMINFOCustomerServiceUnit;
			}
			set
			{
				if ((this._COMINFOCustomerServiceUnit != value))
				{
					this._COMINFOCustomerServiceUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOBusCustomerServiceUnit", DbType="Bit NOT NULL")]
		public bool COMINFOBusCustomerServiceUnit
		{
			get
			{
				return this._COMINFOBusCustomerServiceUnit;
			}
			set
			{
				if ((this._COMINFOBusCustomerServiceUnit != value))
				{
					this._COMINFOBusCustomerServiceUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMINFOCOMINFOOrder", DbType="Int")]
		public System.Nullable<int> COMINFOCOMINFOOrder
		{
			get
			{
				return this._COMINFOCOMINFOOrder;
			}
			set
			{
				if ((this._COMINFOCOMINFOOrder != value))
				{
					this._COMINFOCOMINFOOrder = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
